Notebook to code
remla2022/stackoverflow-tagger pull request #11
Opened 2022-06-05 21:50 UTC by kbaran1998

2022-06-06 14:06 UTC, kponichtera requested changes

2022-06-06 14:06 UTC, kponichtera commented on Taskfile.yml
> +    - source python-version.sh
This should be realized through `preconditions`: https://taskfile.dev/usage/#using-programmatic-checks-to-cancel-execution-of-an-task-and-its-dependencies

2022-06-06 14:06 UTC, kponichtera commented on learning_service/src/get_data.py
> +DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
We should externalize both of these to the properties, with the use of Dataconf that Calin implemented (and which is already merged to the master, if I am correct).

2022-06-06 14:06 UTC, kponichtera commented on learning_service/notebooks/requirements.notebook.txt
> +ipykernel
Would be great to use requirements freeze to settle on the library versions for both learning and inference services.

2022-06-06 15:52 UTC, kbaran1998 commented on learning_service/src/get_data.py
> +DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
I saw something similar in the inference service in [config directory](https://github.com/remla2022/stackoverflow-tagger/tree/master/interface_service/src/configs) and [config.py file](https://github.com/remla2022/stackoverflow-tagger/blob/master/interface_service/src/config.py) on the `master` branch. Is that what you are describing?

2022-06-06 16:04 UTC, kbaran1998 commented on learning_service/notebooks/requirements.notebook.txt
> +ipykernel
I froze then in the learning service.

2022-06-07 12:23 UTC, kponichtera commented on learning_service/src/get_data.py
> +DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
Yes, exactly.

2022-06-07 21:49 UTC, kbaran1998 commented on learning_service/src/get_data.py
> +DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
Added Dynaconf!

2022-06-07 22:19 UTC, kponichtera requested changes

2022-06-07 22:19 UTC, kponichtera commented on learning_service/src/text_preprocessing.py
> +OUTPUT_PATH = os.path.join(ROOT_DIR, settings.OUTPUT_DIR)
There is no need for joining with any kind of root dir - the variables with settings should have absolute/relative path already there.

Also, I know it's not beautiful, but using the enum values can give us at least an illusion of strong typing and highlight whenever a removed property is used or its name  is written with a typo.

```python
DATA_PATH = settings[VarNames.DATASET_FOR_TRAINING_DIR.value]
OUTPUT_PATH = settings[VarNames.OUTPUT_DIR.value]
```

2022-06-08 17:50 UTC, kponichtera approved these changes

2022-06-08 21:09 UTC, merged