Bucket
remla2022/stackoverflow-tagger pull request #23
Opened 2022-06-14 10:40 UTC by kbaran1998

2022-06-14 11:14 UTC, kponichtera requested changes

2022-06-14 11:14 UTC, kponichtera commented on src/interface_service/requirements.txt
> +scikit-learn==0.24.1
Version 0.24.1 is incompatible with Python 3.10 and makes the Docker image building fail.

2022-06-14 16:44 UTC, Cornul11 commented
You've upgraded the scikit-learn version of the learning_service, not interface_service. The updated version of it also seems to need `gcc` in the container.

2022-06-14 17:34 UTC, kbaran1998 commented
> You've upgraded the scikit-learn version of the learning_service, not interface_service. The updated version of it also seems to need `gcc` in the container.

I know. I checked if the upgrading version of `scikit-learn` works locally and it does but we are now facing new problems while running in containers: volume permissions.

2022-06-15 17:13 UTC, kponichtera approved these changes
LGTM, but there is still CSV caching to implement.

2022-06-15 17:14 UTC, merged